version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    container_name: task
    networks:
      - caddy
    volumes:
      - ./:/var/www/html

networks:
  caddy:
    external: true